import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {HybridVolume} from './hybrid-volume.js?v=067.2';
import {createFrameScheduler} from './scheduler.js?v=035.1';
import {createRenderQuality} from './render-quality.js?v=064.1';
const $=id=>document.getElementById(id),host=$('viewport');
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(31,1,.005,12);camera.position.set(0,.08,-.38);scene.background=new THREE.Color('#151616');
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setPixelRatio(1);host.append(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.autoRotateSpeed=.22*6;controls.minDistance=.14;controls.maxDistance=3.5;
const hybrid=new HybridVolume(renderer,scene,camera),quality=createRenderQuality();
const state={brainOpacity:.55,brainLighting:1,brainColor:'#a8dce9',brainDepth:[0,.5],layers:{}};
const defaults={
 'skin-outer':['Skin & outer',true,.05,'#c99d88'],bone:['Bone tissues',true,.03,'#e2d0ac'],eyes:['Eyes',true,.04,'#aacbd5'],
 'head037-mixed':['Mixed soft tissues · includes muscle',false,.15,'#b9807a'],
 arterial:['Arterial candidates',true,1,'#f66d55'],venous:['Venous candidates',true,1,'#459ddb'],uncertain:['Vessels · type uncertain',true,1,'#e3af55'],'unclassified-scan':['Unclassified scan signal',false,1,'#a4afb7'],brain:['Native brain context',true,.55,'#a8dce9'],
 'cortex023-gray':['Cortical gray matter',true,.55,'#c3c5db'],'cortex023-white':['Cerebral white matter',false,.55,'#d9ddd5'],'cortex023-deep-gray':['Deep gray structures',false,.55,'#b2a4c7'],'cortex023-cerebellum':['Cerebellum',true,.55,'#b0bfce'],'cortex023-brainstem':['Brainstem',true,.55,'#d2afa0'],'cortex023-ventricles':['Ventricular fluid',true,1,'#829bc6'],
 ...Object.fromEntries(['left-lateral','right-lateral','third','fourth'].map((k,i)=>['ventricles-presentation::ventricle-'+k,[['Left lateral fluid · partial','Right lateral fluid · partial','Third ventricle fluid · partial','Fourth ventricle fluid · partial'][i],true,1,'#829bc6']]))};
for(const [k,[_name,visible,opacity,color]]of Object.entries(defaults))state.layers[k]={visible,opacity,color,lighting:1};
const absent={visible:false,opacity:0,color:'#aacbd5',lighting:1},layer=k=>state.layers[k]||absent;
const groups=[['skin-layers','Skin & outer layers',['skin-outer','head037-mixed']],['bone-tissues','Bone tissues',['bone']],['eyes','Eyes',['eyes']],['vessel-views','Vessels',['arterial','venous','uncertain','unclassified-scan']],['brain-tissues','Brain',['brain','cortex023-gray','cortex023-white','cortex023-deep-gray','cortex023-cerebellum','cortex023-brainstem']],['fluid-spaces','Fluid spaces',['cortex023-ventricles',...Object.keys(defaults).filter(k=>k.startsWith('ventricles-presentation'))]]];
let current=null,lastInteraction=-Infinity,settleTimer=null,qualityPoll=null,dirty=true,defaultFraming=true,elapsed=0,warmups=0,fallback=null;
const sampling={step_mm:.45,max_step_mm:1.5,target_ms:1000/60,gpu_ms:null};
const gpu=renderer.getContext(),timer=renderer.extensions.get('EXT_disjoint_timer_query_webgl2');let pendingTimer=null,timedPixels=0,timedFull=false,timedMoving=false;
const rowNodes=new Map(),groupNodes=new Map();
const intro={active:false,waiting:false,phase:'idle',fence:null,delayUntil:0,last:0,seconds:0,renderedAt:0,motionStartedAt:0,presentedFrames:0,hiddenAt:null};
function stopIntro(){if(intro.fence)gpu.deleteSync(intro.fence);intro.fence=null;intro.active=false;intro.waiting=false;intro.phase='idle';intro.hiddenAt=null;current?.pinnedSlots?.clear();renderer.domElement.style.visibility='visible';}
function startIntro(){stopIntro();intro.active=true;intro.waiting=true;intro.phase='loading';intro.seconds=0;intro.renderedAt=0;intro.motionStartedAt=0;intro.presentedFrames=0;controls.autoRotate=false;refreshMotion();current.pinnedSlots=new Set(['head037']);renderer.domElement.style.visibility='hidden';notice('Loading default view…');apply();}
function introAssetsReady(){return !hybrid.structures.pending.size&&!hybrid.structures.slots.some(s=>s.wanted&&s.data.loaded===false)&&!hybrid.structures.failures.size;}
function advanceIntro(time){
 if(!intro.active)return;
 if(intro.phase==='loading'){
  if(hybrid.structures.failures.size){stopIntro();notice('A selected layer could not load. Reload to retry.',true);return;}
  if(!intro.fence)return;
  const status=gpu.clientWaitSync(intro.fence,0,0);if(status===gpu.WAIT_FAILED){stopIntro();notice('The default view could not finish rendering. Reload to retry.',true);return;}
  if(status!==gpu.ALREADY_SIGNALED&&status!==gpu.CONDITION_SATISFIED)return;
  gpu.deleteSync(intro.fence);intro.fence=null;intro.waiting=false;intro.phase='hold';intro.renderedAt=time;intro.delayUntil=time+1000;renderer.domElement.style.visibility='visible';notice('');return;
 }
 if(intro.phase==='hold'){if(time<intro.delayUntil)return;intro.phase='fading';intro.last=time;intro.seconds=0;intro.motionStartedAt=time;controls.autoRotate=true;refreshMotion();}
 // Keep a stalled draw from skipping a visible transition; at normal frame rates each stage lasts3seconds.
 intro.seconds+=Math.max(0,Math.min(.1,(time-intro.last)/1000));intro.last=time;
 const seconds=intro.seconds,ease=x=>{x=THREE.MathUtils.clamp(x,0,1);return x*x*(3-2*x);};let skin=1,bone=1;
 if(seconds<3)skin=1-ease(seconds/3);else if(seconds<6){skin=0;bone=1-ease((seconds-3)/3);}else if(seconds<11){skin=0;bone=0;}else if(seconds<14){skin=0;bone=ease((seconds-11)/3);}else if(seconds<17)skin=ease((seconds-14)/3);else stopIntro();
 layer('skin-outer').opacity=defaults['skin-outer'][2]*skin;layer('bone').opacity=defaults.bone[2]*bone;apply();
}
function cancelIntroForControl(event){if(event.target.closest('button,input,select,a')?.id!=='defaultView')stopIntro();}
for(const type of ['pointerdown','click','input','change','keydown'])document.addEventListener(type,cancelIntroForControl,true);
document.addEventListener('visibilitychange',()=>{if(!intro.active)return;if(document.hidden)intro.hiddenAt=performance.now();else if(intro.hiddenAt!==null){const pause=performance.now()-intro.hiddenAt;intro.delayUntil+=pause;intro.last+=pause;intro.hiddenAt=null;}});

function notice(t,error=false){$('loadNotice').hidden=!t;$('loadNotice').textContent=t;$('loadNotice').classList.toggle('error',error);}
function invalidate(){dirty=true;scheduler.wake();}
function moving(){return controls.autoRotate||intro.active&&intro.phase==='fading'||performance.now()-lastInteraction<250;}
function interaction(){lastInteraction=performance.now();clearTimeout(settleTimer);settleTimer=setTimeout(invalidate,310);invalidate();}
function apply(){state.brainOpacity=layer('brain').visible?layer('brain').opacity:0;state.brainLighting=layer('brain').lighting;state.brainColor=layer('brain').color;if(current)hybrid.sync(current,state,layer,'glass',1);refreshUI();invalidate();}
function refreshUI(){for(const [k,n]of rowNodes){const l=layer(k);n.check.checked=l.visible;n.opacity.value=Math.round(l.opacity*100);n.output.value=n.opacity.value+'%';n.color.value=l.color;}for(const n of groupNodes.values()){const colours=n.keys.map(k=>layer(k).color),mixed=colours.some(c=>c!==colours[0]);n.color.value=colours[0];n.color.dataset.mixed=String(mixed);n.color.title=mixed?'Mixed colours · choose to set every layer':'Sets every layer in this category';const on=n.keys.map(layer).filter(l=>l.visible);n.check.checked=on.length>0;n.check.indeterminate=on.length>0&&on.length<n.keys.length;n.slider.disabled=!on.length;const p=on.map(l=>Math.round(l.opacity*100));n.slider.value=p.length?Math.round(p.reduce((a,b)=>a+b,0)/p.length):0;const lo=Math.min(...p),hi=Math.max(...p);n.output.value=!p.length?'None':lo===hi?lo+'%':lo+'–'+hi+'%';}const max=hybrid.depthMaxMM||50;for(const [id,i]of [['brainDepthMin',0],['brainDepthMax',1],['brainDepthMinNumber',0],['brainDepthMaxNumber',1]]){if($(id)){$(id).max=max;$(id).value=state.brainDepth[i];}}if($('brainDepthTrack')){$('brainDepthTrack').style.setProperty('--from',state.brainDepth[0]/max*100+'%');$('brainDepthTrack').style.setProperty('--to',state.brainDepth[1]/max*100+'%');$('brainDepthValue').value=state.brainDepth.map(v=>+v.toFixed(1)).join('–')+' mm';}}
function makeLayer(k){const row=document.createElement('div');row.className='layer';row.dataset.structure=k;row.innerHTML=`<div class="layer-top"><input type="checkbox" id="layer-${k}" data-layer="${k}"><label for="layer-${k}">${defaults[k][0]}</label><input type="color" aria-label="${defaults[k][0]} colour"></div><label>Opacity <output data-opacity-value="${k}"></output><input type="range" min="0" max="100" data-opacity="${k}" aria-label="${defaults[k][0]} opacity"></label>`;const [check,color,opacity]=row.querySelectorAll('input'),[output]=row.querySelectorAll('output');rowNodes.set(k,{check,color,opacity,output});check.onchange=()=>{layer(k).visible=check.checked;apply();};color.oninput=()=>{layer(k).color=color.value;apply();};opacity.oninput=()=>{layer(k).opacity=+opacity.value/100;apply();};return row;}
function buildLayers(){for(const [id,name,keys]of groups){
 const group=document.createElement('section');group.className='layer-group';group.dataset.group=id;
 const heading=document.createElement('div');heading.className='group-heading';
 const check=document.createElement('input');check.type='checkbox';check.id='group-'+id;check.dataset.groupVisibility=id;
 const label=document.createElement('label');label.htmlFor=check.id;label.textContent=name;check.setAttribute('aria-label','Show or hide '+name);heading.append(check,label);
 const shared=document.createElement('div');shared.className='group-controls';shared.innerHTML=`<label class="group-opacity">Opacity <output></output><input type="range" min="0" max="100" data-group-opacity="${id}" aria-label="${name} opacity"></label><input type="color" data-group-color="${id}" aria-label="${name} colour for all layers">`;
 group.append(heading,shared);const slider=shared.querySelector('input[type=range]'),output=shared.querySelector('output'),color=shared.querySelector('input[type=color]');
 groupNodes.set(id,{check,slider,output,color,keys,previous:null});
 color.oninput=()=>{keys.forEach(k=>layer(k).color=color.value);apply();};
 check.onchange=()=>{const n=groupNodes.get(id);if(!check.checked){n.previous=Object.fromEntries(keys.map(k=>[k,layer(k).visible]));keys.forEach(k=>layer(k).visible=false);}else{const restore=keys.some(k=>n.previous?.[k]);keys.forEach(k=>layer(k).visible=restore?n.previous[k]===true:true);n.previous=null;}apply();};
 slider.oninput=()=>{keys.filter(k=>layer(k).visible).forEach(k=>layer(k).opacity=+slider.value/100);apply();};
 let body=null;if(keys.length>1){const detail=document.createElement('details');detail.className='group-details';const summary=document.createElement('summary');summary.textContent='Individual layers';body=document.createElement('div');body.className='group-body';for(const k of keys)body.append(makeLayer(k));detail.append(summary,body);group.append(detail);}$('layers').append(group);
 if(id==='brain-tissues'){const depth=document.createElement('div');depth.className='depth';depth.innerHTML='<div class="depth-title"><span>Brain envelope depth</span><output id="brainDepthValue"></output></div><div class="depth-track" id="brainDepthTrack"><input id="brainDepthMin" type="range" min="0" max="50" step="0.5" aria-label="Minimum brain depth"><input id="brainDepthMax" type="range" min="0" max="50" step="0.5" aria-label="Maximum brain depth"></div><div class="depth-numbers"><input id="brainDepthMinNumber" type="number" min="0" max="50" step="0.5" aria-label="Minimum brain depth in millimetres"><span>to</span><input id="brainDepthMaxNumber" type="number" min="0" max="50" step="0.5" aria-label="Maximum brain depth in millimetres"><span>mm</span></div><div class="depth-presets"><button data-depth-preset="whole">Whole brain</button><button data-depth-preset="outer">Outer shell</button><button data-depth-preset="inner">Inner band</button></div>';body.prepend(depth);}}
for(const [id,i]of [['brainDepthMin',0],['brainDepthMax',1],['brainDepthMinNumber',0],['brainDepthMaxNumber',1]])$(id).oninput=()=>{const v=+$(id).value,max=hybrid.depthMaxMM||50;if(!Number.isFinite(v))return;state.brainDepth[i]=i===0?Math.max(0,Math.min(v,state.brainDepth[1]-.5)):Math.min(max,Math.max(v,state.brainDepth[0]+.5));apply();};for(const b of document.querySelectorAll('[data-depth-preset]'))b.onclick=()=>{const max=hybrid.depthMaxMM||50;state.brainDepth=b.dataset.depthPreset==='outer'?[0,Math.min(4,max)]:b.dataset.depthPreset==='inner'?[Math.min(4,max-.5),Math.min(20,max)]:[0,max];apply();};refreshUI();}
function size(){const r=host.getBoundingClientRect();return {width:Math.max(1,Math.floor(r.width)),height:Math.max(1,Math.floor(r.height))};}
function resize(){const {width,height}=size();renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix();if(current&&defaultFraming)fit();invalidate();}
function fit(){
 const d=hybrid.datasets[1],b=d.entry.brainIndexBounds,brainBox=new THREE.Box3();for(const x of [b[0][0],b[1][0]])for(const y of [b[0][1],b[1][1]])for(const z of [b[0][2],b[1][2]])brainBox.expandByPoint(new THREE.Vector3(x,y,z).applyMatrix4(d.m));current.root.position.copy(brainBox.getCenter(new THREE.Vector3())).negate();
 const model=hybrid.structures.slots.find(s=>s.id==='head037').data,limits=model.entry.defaultViewIndexBounds,points=[];
 for(const x of [limits[0][0],limits[1][0]])for(const y of [limits[0][1],limits[1][1]])for(const z of [limits[0][2],limits[1][2]])points.push(new THREE.Vector3(x,y,z).applyMatrix4(model.m).add(current.root.position));
 const box=new THREE.Box3().setFromPoints(points),centre=box.getCenter(new THREE.Vector3()),dir=camera.position.clone().sub(controls.target).normalize(),right=new THREE.Vector3().crossVectors(camera.up,dir).normalize(),up=new THREE.Vector3().crossVectors(dir,right).normalize(),tan=Math.tan(THREE.MathUtils.degToRad(camera.fov)/2),view=points.map(p=>{const v=p.clone().sub(centre);return {x:v.dot(right),y:v.dot(up),z:v.dot(dir)};});
 const ranges=distance=>{let lx=-Infinity,hx=Infinity,ly=-Infinity,hy=Infinity;for(const p of view){const height=.9*tan*(distance-p.z),width=height*camera.aspect;lx=Math.max(lx,p.x-width);hx=Math.min(hx,p.x+width);ly=Math.max(ly,p.y-height);hy=Math.min(hy,p.y+height);}return {lx,hx,ly,hy};};
 let lo=Math.max(.14,...view.map(p=>p.z+camera.near)),hi=3.5;for(let i=0;i<40;i++){const mid=(lo+hi)/2,r=ranges(mid);if(r.lx<=r.hx&&r.ly<=r.hy)hi=mid;else lo=mid;}const r=ranges(hi);controls.target.copy(centre).addScaledVector(right,(r.lx+r.hx)/2).addScaledVector(up,(r.ly+r.hy)/2);camera.position.copy(controls.target).addScaledVector(dir,hi);controls.update();apply();
}
function consumeTiming(){if(!timer||!pendingTimer||!gpu.getQueryParameter(pendingTimer,gpu.QUERY_RESULT_AVAILABLE))return;if(!gpu.getParameter(timer.GPU_DISJOINT_EXT)&&!timedFull){sampling.gpu_ms=gpu.getQueryParameter(pendingTimer,gpu.QUERY_RESULT)/1e6;quality.observe(sampling.gpu_ms,timedPixels,'gpu',timedMoving===moving()?(timedMoving?'moving':'still'):'ignore');if(timedMoving&&quality.inspect().mode!=='detail'){if(sampling.gpu_ms>sampling.target_ms*1.08)sampling.step_mm=Math.min(1.5,sampling.step_mm*1.12);else if(sampling.gpu_ms<sampling.target_ms*.75)sampling.step_mm=Math.max(.45,sampling.step_mm*.94);}}gpu.deleteQuery(pendingTimer);pendingTimer=null;}
function pollTiming(attempt=0){qualityPoll=null;if(document.hidden||!pendingTimer)return;if(gpu.getQueryParameter(pendingTimer,gpu.QUERY_RESULT_AVAILABLE)){consumeTiming();const {width,height}=size(),r=quality.ratio(width,height,devicePixelRatio,false,moving());if((quality.inspect().mode!=='detail'&&quality.inspect().samples<3&&warmups++<2)||Math.abs(r-renderer.getPixelRatio())/renderer.getPixelRatio()>.03)invalidate();}else if(attempt<15)qualityPoll=setTimeout(()=>pollTiming(attempt+1),80);}
function renderFrame(full=false){if(!current)return;consumeTiming();const {width,height}=size(),motion=moving(),now=performance.now();if(!timer&&motion&&!full&&fallback&&now-fallback.start<3000)quality.observe(now-fallback.start,fallback.pixels,'frame interval');const ratio=quality.ratio(width,height,devicePixelRatio,full,motion);if(Math.abs(renderer.getPixelRatio()-ratio)>.001)renderer.setPixelRatio(ratio);const mode=quality.inspect().mode,step=motion&&!full&&mode!=='detail'?(mode==='mobile'?1.5:sampling.step_mm):.45;hybrid.u.stepMM.value=step;hybrid.sync(current,state,layer,'glass',1);const pixels=gpu.drawingBufferWidth*gpu.drawingBufferHeight;let q=null;if(timer&&!pendingTimer){q=gpu.createQuery();gpu.beginQuery(timer.TIME_ELAPSED_EXT,q);timedPixels=pixels;timedFull=full;timedMoving=motion;}try{renderer.setScissorTest(false);renderer.setViewport(0,0,width,height);hybrid.render(current);if(intro.active&&!intro.fence&&(intro.phase==='fading'||intro.phase==='loading'&&introAssetsReady())){intro.fence=gpu.fenceSync(gpu.SYNC_GPU_COMMANDS_COMPLETE,0);gpu.flush();}}finally{renderer.setScissorTest(false);if(q){gpu.endQuery(timer.TIME_ELAPSED_EXT);pendingTimer=q;clearTimeout(qualityPoll);if(!full)qualityPoll=setTimeout(()=>pollTiming(),80);}}fallback=motion&&!full?{start:now,pixels}:null;publish();}
function animate(_time,dt){if(document.hidden||!current)return;elapsed+=dt;if(intro.active&&intro.phase==='fading'&&intro.fence){const status=gpu.clientWaitSync(intro.fence,0,0);if(status===gpu.TIMEOUT_EXPIRED)return;if(status===gpu.WAIT_FAILED){stopIntro();notice('The animation could not finish rendering. Reload to retry.',true);return;}gpu.deleteSync(intro.fence);intro.fence=null;intro.presentedFrames++;}const motionDelta=intro.phase==='fading'?Math.max(0,Math.min(.1,(_time-intro.last)/1000)):dt;advanceIntro(_time);controls.update(motionDelta);if(dirty||moving()){if(intro.active&&(intro.fence||intro.phase==='hold'))return;renderFrame();dirty=false;}}
const scheduler=createFrameScheduler(animate,()=>moving()||intro.active);controls.addEventListener('start',()=>{defaultFraming=false;stopIntro();interaction();});controls.addEventListener('change',()=>controls.autoRotate?invalidate():interaction());controls.addEventListener('end',interaction);
const rememberKey='adambrain:studio061:view:v1',legacyKey='adambrain:studio030:view:v1',savedControls=['renderQuality','orbitSpeed'];
function validArray(v,n){return Array.isArray(v)&&v.length===n&&v.every(Number.isFinite);}
function mergeLegacy(data){const old=data.state?.layers||{},s={};for(const k of Object.keys(defaults))if(old[k])s[k]=old[k];for(const [k,members]of [['eyes',['eye-left','eye-right']],['bone',['head037-compact','head037-cancellous']],['skin-outer',['head-envelope','head037-skin','head037-fat']]]){const selected=members.map(k=>old[k]).filter(l=>l?.visible);if(selected.length)s[k]={...layer(k),visible:true,opacity:selected.reduce((a,l)=>a+l.opacity,0)/selected.length,color:selected[0].color,lighting:selected[0].lighting??1};else if(members.some(k=>old[k]))s[k]={...layer(k),visible:false};}s.brain={...layer('brain'),visible:(data.state?.brainOpacity??.45)>0,opacity:data.state?.brainOpacity??.45,color:data.state?.brainColor||layer('brain').color,lighting:data.state?.brainLighting??1};return {...data,state:{...data.state,layers:s}};}
function restoreData(data){stopIntro();defaultFraming=false;if(!data||data.study==='spine')throw Error('No compatible brain/head view.');if(data.version===1)data=mergeLegacy(data);for(const [k,v]of Object.entries(data.state?.layers||{}))if(defaults[k]&&typeof v.visible==='boolean'&&Number.isFinite(v.opacity)&&/^#[\da-f]{6}$/i.test(v.color))Object.assign(layer(k),{visible:v.visible,opacity:THREE.MathUtils.clamp(v.opacity,0,1),color:v.color,lighting:1});if(validArray(data.state?.brainDepth,2)&&data.state.brainDepth[1]-data.state.brainDepth[0]>=.5&&data.state.brainDepth[0]>=0&&data.state.brainDepth[1]<=(hybrid.depthMaxMM||50))state.brainDepth=[...data.state.brainDepth];for(const id of savedControls){const e=$(id),v=data.controls?.[id];if(v===undefined)continue;if(e.tagName==='SELECT'){if([...e.options].some(o=>o.value===v))e.value=v;}else if(e.type==='range'){if(Number.isFinite(+v))e.value=Math.max(+e.min,Math.min(+e.max,+v));}else if(e.type==='color'&&/^#[\da-f]{6}$/i.test(v))e.value=v;}if(validArray(data.camera,3)&&validArray(data.target,3)){camera.position.fromArray(data.camera);controls.target.fromArray(data.target);}controls.autoRotate=false;refreshMotion();controls.update();updateAppearance();apply();}
function refreshMotion(){$('motionToggle').textContent=controls.autoRotate?'Stop':'Start';$('motionToggle').setAttribute('aria-pressed',String(controls.autoRotate));$('motionToggle').setAttribute('aria-label',controls.autoRotate?'Stop motion':'Start motion');}
function updateAppearance(){controls.autoRotateSpeed=.22*+$('orbitSpeed').value;$('orbitSpeedValue').value=+$('orbitSpeed').value+'×';quality.setMode($('renderQuality').value);}
function publish(){window.studioSummary={revision:'068.2',status:window.studioReady?'ready':'loading',camera:camera.position.toArray(),target:controls.target.toArray(),brainDepth:[...state.brainDepth],intro:{active:intro.active,waiting:intro.waiting,phase:intro.phase,seconds:intro.seconds},layers:structuredClone(state.layers),source:hybrid.ready?hybrid.inspect():null,quality:quality.inspect(),sampling:{...sampling,active_step_mm:hybrid.u?.stepMM.value},screen:{width:gpu.drawingBufferWidth,height:gpu.drawingBufferHeight,pixels:gpu.drawingBufferWidth*gpu.drawingBufferHeight},scheduler:{...scheduler.stats,pending:scheduler.pending},clock:elapsed};return window.studioSummary;}
window.inspectStudio=publish;window.reconstructionTest={renderer,camera,controls,state,hybrid,layer,apply,renderFrame,fit,quality,scheduler,get current(){return current;},restoreData,stop(){controls.autoRotate=false;stopIntro();refreshMotion();apply();},advanceIntro,startIntro,get intro(){return intro;}};
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(t=>t.classList.toggle('active',t===b));document.querySelectorAll('[data-pane]').forEach(p=>p.hidden=p.dataset.pane!==b.dataset.tab);};
$('panelToggle').onclick=()=>{$('panel').hidden=!$('panel').hidden;document.body.classList.toggle('panel-closed',$('panel').hidden);$('panelToggle').setAttribute('aria-expanded',String(!$('panel').hidden));resize();};$('motionToggle').onclick=()=>{controls.autoRotate=!controls.autoRotate;refreshMotion();interaction();};
for(const id of savedControls)$(id).addEventListener('input',()=>{if(id==='renderQuality'){quality.setMode($(id).value);warmups=0;}if(id==='orbitSpeed')controls.autoRotateSpeed=.22*+$(id).value;if($(id+'Value'))$(id+'Value').value=$(id).value+(id==='orbitSpeed'?'×':'%');apply();});
$('defaultView').onclick=()=>{stopIntro();defaultFraming=true;controls.autoRotate=false;for(const [k,[_name,visible,opacity,color]]of Object.entries(defaults))Object.assign(layer(k),{visible,opacity,color,lighting:1});state.brainDepth=[0,.5];$('orbitSpeed').value=6;$('renderQuality').value='auto';warmups=0;camera.position.copy(controls.target).add(new THREE.Vector3(0,.08,-.38));updateAppearance();$('panel').hidden=false;document.body.classList.remove('panel-closed');$('panelToggle').setAttribute('aria-expanded','true');resize();controls.autoRotate=false;refreshMotion();$('sessionStatus').value='Default view restored.';apply();if(current)startIntro();};
$('saveSession').onclick=()=>{try{localStorage.setItem(rememberKey,JSON.stringify({version:2,study:'head',state,camera:camera.position.toArray(),target:controls.target.toArray(),controls:Object.fromEntries(savedControls.map(id=>[id,$(id).value]))}));$('sessionStatus').value='Saved in this browser.';}catch(e){$('sessionStatus').value=e.message;}};
$('restoreSession').onclick=()=>{try{restoreData(JSON.parse(localStorage.getItem(rememberKey)||localStorage.getItem(legacyKey)||'null'));$('sessionStatus').value='View restored.';}catch(e){$('sessionStatus').value=e.message;}};$('clearSession').onclick=()=>{try{localStorage.removeItem(rememberKey);localStorage.removeItem(legacyKey);$('sessionStatus').value='Saved view cleared.';}catch(e){$('sessionStatus').value=e.message;}};
$('snapshot').onclick=()=>{try{renderFrame(true);const a=document.createElement('a');a.download='adambrain-view.png';a.href=renderer.domElement.toDataURL('image/png');a.click();}catch(e){notice('Image unavailable: '+e.message,true);}finally{renderFrame(false);}};
renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();scheduler.stop();clearTimeout(qualityPoll);pendingTimer=null;$('contextRecovery').hidden=false;});renderer.domElement.addEventListener('webglcontextrestored',()=>location.reload());
addEventListener('structures-ready',()=>{if(current){apply();notice('');}});addEventListener('structures-loading',()=>{const v=[hybrid.structures];if(v.some(s=>s.failures.size))notice('A selected layer could not load. Reload to retry.',true);else if(v.some(s=>s.pending.size))notice('Loading selected layers…');});addEventListener('source-progress',e=>{if(!window.studioReady)notice('Loading scans · '+(e.detail.encodedBytes/1e6).toFixed(1)+' MB');});
addEventListener('pagehide',()=>{scheduler.dispose();clearTimeout(qualityPoll);clearTimeout(settleTimer);renderer.dispose();});new ResizeObserver(resize).observe(host);buildLayers();resize();
(async()=>{try{await hybrid.initialize('./data/volume-groups.json');current={study:'head',edition:'008',root:new THREE.Group(),meshes:Object.fromEntries(Object.keys(defaults).map(k=>[k,[]]))};scene.add(current.root);fit();controls.autoRotate=false;refreshMotion();window.studioReady=true;$('snapshot').disabled=false;notice('');apply();startIntro();}catch(e){notice('Viewer could not start: '+e.message,true);console.error(e);}})();
